---
- name: Install zookeeper
  apt:
    name: zookeeper
    state: latest
- name: Install zookeeperd
  apt:
    name: zookeeperd
    state: latest
- name: Add Confluent key
  apt_key:
    url: "{{ confluent_key }}"
    state: present
- name: Add Confluent repository
  apt_repository:
    repo: "{{ confluent_repo }}"
    state: present
    update_cache: yes
- name: Install Confluent platform
  apt:
    name: confluent-platform-oss-2.11
    state: latest
- name: setup group
  group:
    name: kafka
    system: yes
- name: setup user
  user: 
    name: kafka
    system: yes
    group: kafka
- name: create and set permissions on kafka directory
  file:
    state: directory
    path: /var/lib/kafka
    owner: kafka
    group: kafka
    mode: 0755
- name: create and set permissions on kafka log directory
  file:
    state: directory
    path: /var/log/kafka
    owner: kafka
    group: kafka
    mode: 0755
- name: copy kafka service
  copy:
    src: kafka.service
    dest: /etc/systemd/system/kafka.service
- name: copy kafka server config
  template:
    src: server.properties.j2
    dest: /etc/kafka/server.properties
- name: create private directory
  file:
    state: directory
    path: /var/private
    owner: root
    group: root
    mode: 0755
- name: create kafka key directory
  file:
    state: directory
    path: /var/private/kafka
    owner: kafka
    group: kafka
    mode: 0755
- name: copy keyfile
  copy:
    src: '{{ inventory_hostname }}.kafka.server.keystore.jks'
    dest: /var/private/kafka
    owner: root
    group: kafka
    mode: 0750
- name: copy truststore
  copy:
    src: '{{ inventory_hostname }}.kafka.server.truststore.jks'
    dest: /var/private/kafka
    owner: root
    group: kafka
    mode: 0750
- name: start kafka
  systemd:
    name: kafka
    state: restarted
    enabled: yes
